// <auto-generated />
using Mango.services.ProductApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.services.ProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250827100151_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.services.Product.Api.Models.Product1", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "quisque vel lacus",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cubesnjuliennes.com%2Findian-samosa-recipe-punjabi-samosa%2F&psig=AOvVaw1ZGhHb19e6cBFmdU0XQS3h&ust=1756359375355000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLCuhNaiqo8DFQAAAAAdAAAAABAE",
                            Name = "Samosa",
                            Price = 120.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
