
USE MilkMgtSystem
Select * from sys.tables

/*
--INSERT INTO MILKtYPE  VALUES('COW'),('BUFFALO')
--SELECT * FROM MILKTYPE
--Update MILKTYPE SET Dateadded =getdate()

--Alter table MILKtYPE Alter column Dateadded dateTime


CREATE TABLE ROLE(
ROLEID INT IDENTITY(1,2) NOT NULL,
ROLENAME NVARCHAR(255) NOT NULL,
DATEADDED DATETIME,
DATECHANGED DATETIME,
DELETEFLAG BIT
);

ALTER TABLE ROLE
ADD CONSTRAINT PK_ROLE PRIMARY KEY (ROLEID);

INSERT INTO ROLE VALUES('Dealer',GetDate(),Getdate(),0),('Customer',GetDate(),Getdate(),0)



CREATE TABLE CUSTOMER(
CUSTOMERID INT IDENTITY(1,1) NOT NULL,
FIRST_NAME NVARCHAR(250) NOT NULL,
LAST_NAME NVARCHAR(250) NOT NULL,
MOBILENO  NVARCHAR(250) NOT NULL,
ROLEID INT,
MILKTYPEID INT,
DATEADDED DATETIME,
DATECHANGED DATETIME,
DELETEFLAG BIT

FOREIGN KEY (ROLEID) REFERENCES ROLE(ROLEID),
FOREIGN KEY (MILKTYPEID) REFERENCES MILKTYPE(MILKTYPEID)


);

ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMERID);



SELECT * FROM ROLE
sELECT * FROM MILKTYPE
Select * from CUSTOMER
Select * from  MILKCOLLECTION
INSERT INTO  CUSTOMER values('RAM','Sawant','7304288372',1,1,getdate(),getdate(),0),
('Bharat','Sawant','7304288372',3,2,getdate(),getdate(),0)
('Sagar','Sawant','7304288372',3,1,getdate(),getdate(),0),;


CREATE TABLE MILKCOLLECTION
(
CUSTOMERID INT,
MILKTYPEID INT,
LITER DECIMAL,
FAT FLOAT,
SNF FLOAT,
TOTAL DECIMAL,
DATEADDED DATETIME,
GUID NVARCHAR(1000) NOT NULL

FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
FOREIGN KEY (MILKTYPEID) REFERENCES MILKTYPE(MILKTYPEID)
);

DROP TABLE MILKCOLLECTION

ALTER TABLE MILKCOLLECTION
ADD CONSTRAINT PK_MILKCOLLECTION PRIMARY KEY (GUID);

ALTER TABLE MILKCOLLECTION ADD  RATE FLOAT

SELECT * FROM MILKCOLLECTION
--UPDATE MILKCOLLECTION set COLLECTIONSHIFT='Evening' WHERE GUID in('EB226598-F3C7-4F1A-82B9-A4E7438F6FA5')
SELECT * FROM MILKCOLLECTION
SELECT * FROM CUSTOMER
INSERT INTO MILKCOLLECTION VALUES(1,1,1,3.5,8.5,35,GETDATE(),NEWID()),
(2,2,1,7.0,8.5,56,GETDATE(),NEWID())


ALTER TABLE MILKCOLLECTION ADD  COLLECTIONSHIFT NVARCHAR(255)

delete from MILKCOLLECTION 
where GUID='EB226598-F3C7-4F1A-82B9-A4E7438F6FA5'
select * from sys.tables


CREATE TABLE MILKERATE
(
ID INT IDENTITY(1,1) NOT NULL,
FATRATE FLOAT,
SNFRATE FLOAT
)

INSERT INTO MILKERATE VALUES(11,6)

Select * from MILKERATE
Update MILKERATE SET FATRATE=4.2 ,SNFRATE=2.4

Select (4.2 * 3.5) +(2.4 * 8.5);



Alter table MILKCOLLECTION Alter column LITER decimal;


DROP TABLE FoodDetails
CREATE TABLE FoodDetails (
    SRNO INT IDENTITY(1,1) NOT NULL,
    FoodId INT,
    FOODNAME NVARCHAR(250),
    QUANTITY INT NOT NULL,
    RATE INT NOT NULL,
    AMOUNT INT,
    CUSTOMERID INT,
    DATEADDED DATETIME,
    DATECHANGED DATETIME,
    DELETEFLAG BIT,
    
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
    FOREIGN KEY (FoodId) REFERENCES Food(FoodId)
);

ALTER TABLE FoodDetails
ADD CONSTRAINT PK_FoodDetails PRIMARY KEY (SRNO);

 ALTER TABLE Food ADD DATEADDED DATETIME,DATECHANGED DATETIME
ALTER TABLE Food ADD DELETEFLAG BIT
ALTER TABLE Food ADD SRNO INT
INSERT INTO FoodDetails VALUES(1,'HIRA', 1,1700,(1700*1),1,GETDATE(),GETDATE(),0)
INSERT INTO FoodDetails VALUES(1,'HIRA', 2,1700,(1700*2),2,GETDATE(),GETDATE(),0)
SELECT * FROM FoodDetails

UPDATE fOOD SET DELETEFLAG=0
*/


--EXEC sp_rename 'Food', 'FoodDetails';

Create Table Food(
Foodid int identity (1,1) Not Null,
FoodName Nvarchar(250) Not Null,
SellingRate int,
ByingRate Int,
Stock int,
Dateadded datetime,
DateChanged Datetime,
Deleteflag bit
) 
ALTER TABLE Food
ADD CONSTRAINT PK_Food PRIMARY KEY (Foodid);

Select * from FoodDetails;
--delete from FoodDetails where SRNo in(5)
Select * from  Food 

Update Food SET Stock=10
insert into Food values('Makhan dahara',1700,1650,10,Getdate(),Getdate(),0)


